import { type App } from '@/app';
import { authRoutes } from '@/routes/auth.routes';
import { userRoutes } from '@/routes/user.routes';
import { roleRoutes } from '@/routes/role.routes';
import { menuRoutes } from '@/routes/menu.routes';
import { customerRoutes } from './customer.routes';
import { purchaseOrderRoutes } from './purchase-order.routes';
import { supplierRoutes } from './supplier.routes';
import { conversionRoutes } from './conversion.routes';
import { inventoryRoutes } from './inventory.routes';
import { notificationRoutes } from './notification.routes';
import { statusRoutes } from './status.routes';
import { bulkPurchaseOrderRoutes } from './bulk-purchase-order.routes';
import { packingRoutes } from './packing.routes';
import { invoicePengirimanRoutes } from './invoice-pengiriman.routes';
import { invoicePenagihanRoutes } from './invoice-penagihan.routes';
import { fileRoutes } from './file.routes';
import { suratJalanRoutes } from './surat-jalan.routes';
import { historyPengirimanRoutes } from './history-pengiriman.routes';
import { regionRoutes } from './region.routes';
import { termOfPaymentRoutes } from './term-of-payment.routes';
import { companyRoutes } from './company.routes';
import { groupCustomerRoutes } from './group-customer.routes';
import { itemPriceRoutes } from './item-price.routes';
import { laporanPenerimaanBarangRoutes } from './laporan-penerimaan-barang.routes';
import { dimensiKardusRoutes } from './dimensi-kardus.routes';

export default async (fastify: App) => {
  fastify.register(authRoutes, { prefix: '/auth' });
  fastify.register(userRoutes, { prefix: '/users' });
  fastify.register(roleRoutes, { prefix: '/roles' });
  fastify.register(menuRoutes, { prefix: '/menus' });
  fastify.register(customerRoutes, { prefix: '/customers' });
  fastify.register(supplierRoutes, { prefix: '/suppliers' });
  fastify.register(purchaseOrderRoutes, { prefix: '/purchase-orders' });
  fastify.register(conversionRoutes, { prefix: '/conversions' });
  fastify.register(inventoryRoutes, { prefix: '/inventories' });
  fastify.register(notificationRoutes, { prefix: '/notifications' });
  fastify.register(statusRoutes, { prefix: '/statuses' });
  fastify.register(fileRoutes, { prefix: '/files' });
  fastify.register(bulkPurchaseOrderRoutes, { prefix: '/bulk-purchase-order' });
  fastify.register(packingRoutes, { prefix: '/packings' });
  fastify.register(invoicePengirimanRoutes, { prefix: '/invoice-pengiriman' });
  fastify.register(invoicePenagihanRoutes, { prefix: '/invoice-penagihan' });
  fastify.register(suratJalanRoutes, { prefix: '/surat-jalan' });
  fastify.register(regionRoutes, { prefix: '/regions' });
  fastify.register(termOfPaymentRoutes, { prefix: '/term-of-payments' });
  fastify.register(companyRoutes, { prefix: '/companies' });
  fastify.register(groupCustomerRoutes, { prefix: '/group-customers' });
  fastify.register(historyPengirimanRoutes, { prefix: '/history-pengiriman' });
  fastify.register(itemPriceRoutes, { prefix: '/item-prices' });
  fastify.register(laporanPenerimaanBarangRoutes, { prefix: '/laporan-penerimaan-barang' });
  fastify.register(dimensiKardusRoutes, { prefix: '/dimensi-kardus' });
};
